----------------------------------------------------------------------------------
-- Auto-generated by piskel_argb_to_vhdl_gui.py
-- Source C file     : chicken_backward.c
-- Frame             : 0
-- Size              : 30 x 30
-- Output            : color index only; palette is in comments
-- Original colors   : 83
-- Palette source    : Web safe 216 colors
-- Palette size      : 216 color(s)
-- Index width       : 8 bit(s)
-- Mapped/quantized  : yes
-- Notes             : C input interpreted as AABBGGRR. Alpha=0 pixels map to x"000000" / index 0.
----------------------------------------------------------------------------------

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity chicken_backward_index_rom is
    port (
        clk      : in  std_logic;
        en       : in  std_logic;
        row_addr : in  unsigned(4 downto 0);
        col_addr : in  unsigned(4 downto 0);
        color_index : out std_logic_vector(7 downto 0)
    );
end chicken_backward_index_rom;

architecture Behavioral of chicken_backward_index_rom is
    constant SPRITE_WIDTH  : integer := 30;
    constant SPRITE_HEIGHT : integer := 30;

    subtype index_t is std_logic_vector(7 downto 0);
    subtype rgb_t   is std_logic_vector(23 downto 0);

    type row_t    is array (0 to SPRITE_WIDTH - 1) of index_t;
    type sprite_t is array (0 to SPRITE_HEIGHT - 1) of row_t;

-- Palette index map:
--      0 => x"000000"
--      1 => x"000033"
--      2 => x"000066"
--      3 => x"000099"
--      4 => x"0000CC"
--      5 => x"0000FF"
--      6 => x"003300"
--      7 => x"003333"
--      8 => x"003366"
--      9 => x"003399"
--     10 => x"0033CC"
--     11 => x"0033FF"
--     12 => x"006600"
--     13 => x"006633"
--     14 => x"006666"
--     15 => x"006699"
--     16 => x"0066CC"
--     17 => x"0066FF"
--     18 => x"009900"
--     19 => x"009933"
--     20 => x"009966"
--     21 => x"009999"
--     22 => x"0099CC"
--     23 => x"0099FF"
--     24 => x"00CC00"
--     25 => x"00CC33"
--     26 => x"00CC66"
--     27 => x"00CC99"
--     28 => x"00CCCC"
--     29 => x"00CCFF"
--     30 => x"00FF00"
--     31 => x"00FF33"
--     32 => x"00FF66"
--     33 => x"00FF99"
--     34 => x"00FFCC"
--     35 => x"00FFFF"
--     36 => x"330000"
--     37 => x"330033"
--     38 => x"330066"
--     39 => x"330099"
--     40 => x"3300CC"
--     41 => x"3300FF"
--     42 => x"333300"
--     43 => x"333333"
--     44 => x"333366"
--     45 => x"333399"
--     46 => x"3333CC"
--     47 => x"3333FF"
--     48 => x"336600"
--     49 => x"336633"
--     50 => x"336666"
--     51 => x"336699"
--     52 => x"3366CC"
--     53 => x"3366FF"
--     54 => x"339900"
--     55 => x"339933"
--     56 => x"339966"
--     57 => x"339999"
--     58 => x"3399CC"
--     59 => x"3399FF"
--     60 => x"33CC00"
--     61 => x"33CC33"
--     62 => x"33CC66"
--     63 => x"33CC99"
--     64 => x"33CCCC"
--     65 => x"33CCFF"
--     66 => x"33FF00"
--     67 => x"33FF33"
--     68 => x"33FF66"
--     69 => x"33FF99"
--     70 => x"33FFCC"
--     71 => x"33FFFF"
--     72 => x"660000"
--     73 => x"660033"
--     74 => x"660066"
--     75 => x"660099"
--     76 => x"6600CC"
--     77 => x"6600FF"
--     78 => x"663300"
--     79 => x"663333"
--     80 => x"663366"
--     81 => x"663399"
--     82 => x"6633CC"
--     83 => x"6633FF"
--     84 => x"666600"
--     85 => x"666633"
--     86 => x"666666"
--     87 => x"666699"
--     88 => x"6666CC"
--     89 => x"6666FF"
--     90 => x"669900"
--     91 => x"669933"
--     92 => x"669966"
--     93 => x"669999"
--     94 => x"6699CC"
--     95 => x"6699FF"
--     96 => x"66CC00"
--     97 => x"66CC33"
--     98 => x"66CC66"
--     99 => x"66CC99"
--    100 => x"66CCCC"
--    101 => x"66CCFF"
--    102 => x"66FF00"
--    103 => x"66FF33"
--    104 => x"66FF66"
--    105 => x"66FF99"
--    106 => x"66FFCC"
--    107 => x"66FFFF"
--    108 => x"990000"
--    109 => x"990033"
--    110 => x"990066"
--    111 => x"990099"
--    112 => x"9900CC"
--    113 => x"9900FF"
--    114 => x"993300"
--    115 => x"993333"
--    116 => x"993366"
--    117 => x"993399"
--    118 => x"9933CC"
--    119 => x"9933FF"
--    120 => x"996600"
--    121 => x"996633"
--    122 => x"996666"
--    123 => x"996699"
--    124 => x"9966CC"
--    125 => x"9966FF"
--    126 => x"999900"
--    127 => x"999933"
--    128 => x"999966"
--    129 => x"999999"
--    130 => x"9999CC"
--    131 => x"9999FF"
--    132 => x"99CC00"
--    133 => x"99CC33"
--    134 => x"99CC66"
--    135 => x"99CC99"
--    136 => x"99CCCC"
--    137 => x"99CCFF"
--    138 => x"99FF00"
--    139 => x"99FF33"
--    140 => x"99FF66"
--    141 => x"99FF99"
--    142 => x"99FFCC"
--    143 => x"99FFFF"
--    144 => x"CC0000"
--    145 => x"CC0033"
--    146 => x"CC0066"
--    147 => x"CC0099"
--    148 => x"CC00CC"
--    149 => x"CC00FF"
--    150 => x"CC3300"
--    151 => x"CC3333"
--    152 => x"CC3366"
--    153 => x"CC3399"
--    154 => x"CC33CC"
--    155 => x"CC33FF"
--    156 => x"CC6600"
--    157 => x"CC6633"
--    158 => x"CC6666"
--    159 => x"CC6699"
--    160 => x"CC66CC"
--    161 => x"CC66FF"
--    162 => x"CC9900"
--    163 => x"CC9933"
--    164 => x"CC9966"
--    165 => x"CC9999"
--    166 => x"CC99CC"
--    167 => x"CC99FF"
--    168 => x"CCCC00"
--    169 => x"CCCC33"
--    170 => x"CCCC66"
--    171 => x"CCCC99"
--    172 => x"CCCCCC"
--    173 => x"CCCCFF"
--    174 => x"CCFF00"
--    175 => x"CCFF33"
--    176 => x"CCFF66"
--    177 => x"CCFF99"
--    178 => x"CCFFCC"
--    179 => x"CCFFFF"
--    180 => x"FF0000"
--    181 => x"FF0033"
--    182 => x"FF0066"
--    183 => x"FF0099"
--    184 => x"FF00CC"
--    185 => x"FF00FF"
--    186 => x"FF3300"
--    187 => x"FF3333"
--    188 => x"FF3366"
--    189 => x"FF3399"
--    190 => x"FF33CC"
--    191 => x"FF33FF"
--    192 => x"FF6600"
--    193 => x"FF6633"
--    194 => x"FF6666"
--    195 => x"FF6699"
--    196 => x"FF66CC"
--    197 => x"FF66FF"
--    198 => x"FF9900"
--    199 => x"FF9933"
--    200 => x"FF9966"
--    201 => x"FF9999"
--    202 => x"FF99CC"
--    203 => x"FF99FF"
--    204 => x"FFCC00"
--    205 => x"FFCC33"
--    206 => x"FFCC66"
--    207 => x"FFCC99"
--    208 => x"FFCCCC"
--    209 => x"FFCCFF"
--    210 => x"FFFF00"
--    211 => x"FFFF33"
--    212 => x"FFFF66"
--    213 => x"FFFF99"
--    214 => x"FFFFCC"
--    215 => x"FFFFFF"

    constant sprite_rom : sprite_t := (
        0 => (x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8"),
        1 => (x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8"),
        2 => (x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8"),
        3 => (x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"C8", x"C8", x"C8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8"),
        4 => (x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"C8", x"C8", x"C8", x"C2", x"C2", x"D7", x"C5", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8"),
        5 => (x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"C5", x"D7", x"C8", x"C8", x"C2", x"C2", x"C2", x"D7", x"D7", x"D7", x"C5", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8"),
        6 => (x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"D7", x"D7", x"D7", x"C8", x"C8", x"C2", x"A4", x"D7", x"D7", x"D7", x"D7", x"D7", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8"),
        7 => (x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"D7", x"D7", x"D7", x"D6", x"C8", x"D7", x"D7", x"D7", x"D7", x"D1", x"D1", x"D1", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8"),
        8 => (x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"D7", x"D7", x"D7", x"D7", x"D7", x"D7", x"D7", x"D1", x"D1", x"D1", x"D1", x"D1", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8"),
        9 => (x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"D7", x"D6", x"D7", x"D7", x"D7", x"D7", x"D1", x"D1", x"D1", x"D1", x"D1", x"D1", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8"),
        10 => (x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"A0", x"C8", x"C8", x"C8", x"AC", x"D7", x"D7", x"D1", x"4F", x"D1", x"D1", x"D1", x"D1", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8"),
        11 => (x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"C8", x"C8", x"C2", x"C2", x"A5", x"D7", x"D7", x"D1", x"A5", x"D1", x"D1", x"D1", x"D1", x"CB", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8"),
        12 => (x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"C8", x"C8", x"C2", x"C2", x"A5", x"D7", x"D7", x"D1", x"D1", x"D1", x"D1", x"D1", x"D1", x"D7", x"D7", x"D1", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8"),
        13 => (x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"C8", x"C8", x"C2", x"C2", x"A5", x"D7", x"D7", x"D1", x"D1", x"D1", x"D1", x"D1", x"D1", x"D7", x"D7", x"D7", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8"),
        14 => (x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"BE", x"C8", x"C2", x"C2", x"A5", x"D7", x"D7", x"D1", x"D1", x"D1", x"D1", x"D1", x"D1", x"D7", x"D7", x"D1", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8"),
        15 => (x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"D0", x"C2", x"C9", x"D7", x"D7", x"D7", x"D1", x"D1", x"D1", x"D1", x"D1", x"D1", x"D1", x"D1", x"D1", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8"),
        16 => (x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"D7", x"D7", x"D7", x"D7", x"D7", x"D7", x"D1", x"D1", x"D1", x"D1", x"D1", x"D7", x"D7", x"D7", x"D7", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8"),
        17 => (x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"D7", x"D7", x"D7", x"D7", x"D7", x"D7", x"D1", x"D1", x"D1", x"D7", x"D7", x"D7", x"D7", x"D7", x"D1", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8"),
        18 => (x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"D7", x"D7", x"D7", x"D7", x"D7", x"D7", x"D1", x"D7", x"D7", x"D7", x"D7", x"D1", x"D1", x"D1", x"D1", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8"),
        19 => (x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"D7", x"D7", x"D7", x"D7", x"D7", x"D7", x"D1", x"D7", x"D7", x"D7", x"D1", x"D1", x"D1", x"D1", x"D1", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8"),
        20 => (x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"D7", x"D7", x"D7", x"D7", x"D7", x"D7", x"D1", x"D7", x"D7", x"D1", x"D1", x"D1", x"D1", x"D1", x"C5", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8"),
        21 => (x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"C5", x"D7", x"D7", x"D7", x"D7", x"D7", x"D1", x"D7", x"D7", x"D1", x"D1", x"D7", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8"),
        22 => (x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"AC", x"D7", x"D7", x"D7", x"D1", x"D1", x"D0", x"D1", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8"),
        23 => (x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"C8", x"C8", x"C2", x"C8", x"D0", x"D7", x"A5", x"BE", x"C8", x"C2", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8"),
        24 => (x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"C8", x"C2", x"C8", x"C8", x"C2", x"C2", x"BE", x"BE", x"C8", x"C2", x"C3", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8"),
        25 => (x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"A0", x"C8", x"9E", x"9A", x"9F", x"C8", x"C8", x"C8", x"C2", x"C8", x"C2", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8"),
        26 => (x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"C8", x"C2", x"C2", x"C8", x"C2", x"C2", x"BC", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8"),
        27 => (x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"A4", x"C3", x"C2", x"C2", x"9E", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8"),
        28 => (x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"9E", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8"),
        29 => (x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8", x"B8")
    );

begin

    process(clk)
        variable r : integer;
        variable c : integer;
    begin
        if rising_edge(clk) then
            if en = '1' then
                r := to_integer(row_addr);
                c := to_integer(col_addr);
                if r >= 0 and r < SPRITE_HEIGHT and c >= 0 and c < SPRITE_WIDTH then
                    color_index <= sprite_rom(r)(c);
                else
                    color_index <= (others => '0');
                end if;
            else
                color_index <= (others => '0');
            end if;
        end if;
    end process;

end Behavioral;
